const actionTypes = {
    USER_SETTINGS_GET: 'USER_SETTINGS_GET',
    USER_SETTINGS_GET_PROGRESS: 'USER_SETTINGS_GET_PROGRESS',
    USER_SETTINGS_GET_SUCCESS: 'USER_SETTINGS_GET_SUCCESS',
    USER_SETTINGS_GET_FAILED: 'USER_SETTINGS_GET_FAILED',

    USER_SETTINGS_ADD: 'USER_SETTINGS_ADD',
    USER_SETTINGS_ADD_PROGRESS:'USER_SETTINGS_ADD_PROGRESS',
    USER_SETTINGS_ADD_SUCCESS:'USER_SETTINGS_ADD_SUCCESS',
    USER_SETTINGS_ADD_FAILED:'USER_SETTINGS_ADD_FAILED',

    USER_SETTINGS_DELETE: 'USER_SETTINGS_DELETE',
    USER_SETTINGS_DELETE_PROGRESS:'USER_SETTINGS_DELETE_PROGRESS',
    USER_SETTINGS_DELETE_SUCCESS:'USER_SETTINGS_DELETE_SUCCESS',
    USER_SETTINGS_DELETE_FAILED:'USER_SETTINGS_DELETE_FAILED',

};

export default Object.freeze(actionTypes);
